VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsAppMnemonicInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit


Public Mnemonic As String
Public Name As String
Public Description As String
Public LOB As String
Public LOBCIO As String
Public LOBContactGroup As String
Public LOBSupported As String
Public LifecycleStatus As String
Public DataClassification As String
Public CBSTier As String
Public WebAppClass As String
Public DevType As String
Public RTO As String
Public RPO As String
Public SOX As String
Public SOC1 As String
Public OFAC As String
Public AvgConcurrentUsers As String
Public PeakConcurrentUsers As String
Public AvgROTrans As String
Public AvgRWTrans As String
Public AvgTotalTrans As String
Public Mayor As String
Public DomainArch As String
Public IntegrationAnalyst As String
Public ReleaseAnalyst As String
Public MigrationManager As String
Public WaveName As String
Public WaveDate As String


