VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsPtBStatus"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Mnemonic As String
Public MigrationWave As String
Public DDRComplete As String
Public LogicalDesignComplete As String
Public PtBComplete As String

